# Generated by Django 4.0.6 on 2022-09-09 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addactivity',
        ),
    ]
