# Generated by Django 4.0.6 on 2022-09-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_add_ativity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_ativity',
            name='activity_name',
            field=models.CharField(max_length=255),
        ),
    ]
