# Generated by Django 4.0.6 on 2022-09-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_add_ativity_activity_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=255)),
                ('activity', models.CharField(max_length=255)),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
