# Generated by Django 4.0.6 on 2022-09-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_add_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_data_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_user_name', models.CharField(max_length=255)),
                ('add_Id_studen', models.CharField(max_length=255)),
                ('add_f_name', models.CharField(max_length=255)),
                ('add_l_name', models.CharField(max_length=255)),
                ('add_fieldstudy', models.CharField(max_length=255)),
                ('add_activity', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='add_data',
            unique_together={('id_name', 'activity')},
        ),
    ]
