# Generated by Django 4.0.6 on 2022-09-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_add_data_all_alter_add_data_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_data_all',
            name='add_id_activity',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
