# Generated by Django 4.0.6 on 2023-06-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_add_ativity_activity_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_ativity',
            name='activity_icon',
        ),
    ]
